vulnerabilities: []
misconfigurations:
  - id: AVD-DS-0002
    paths:
      - router/Dockerfile
    statement: >
      router/Dockerfile requires root for iptables/NET_ADMIN.
      Other Dockerfiles enforce non-root users.
